version: 2

builds:
  - id: kubectl-lofi
    binary: kubectl-lofi
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: kubectl-lofi
    formats:
      - tar.gz
    name_template: "kubectl-lofi-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
